from __future__ import annotations

from typing import Protocol

from chowki.types import RunRecord, RunStatus, SnapshotEnvelope, StepRecord


class StorageAdapter(Protocol):
    def put_run(self, record: RunRecord) -> None: ...

    def get_run(self, run_id: str) -> RunRecord | None: ...

    def list_runs(self, *, status: RunStatus | None = None) -> list[RunRecord]: ...

    def put_step(self, record: StepRecord) -> None: ...

    def get_step(self, run_id: str, step_id: str) -> StepRecord | None: ...

    def list_steps(self, run_id: str) -> list[StepRecord]: ...

    def put_snapshot(self, env: SnapshotEnvelope) -> None: ...

    def list_snapshots(self, run_id: str) -> list[SnapshotEnvelope]: ...

    def snapshots_for_resume(self, run_id: str) -> list[SnapshotEnvelope]: ...

    def claim_idempotency_key(self, key: str, *, args_hash: str) -> bool: ...

    def consume_nonce(self, nonce: str, *, expires_at_epoch: float | int) -> bool: ...

    def put_blob(self, data: bytes) -> str: ...

    def get_blob(self, ref: str) -> bytes | None: ...

    def append_audit(self, record: dict[str, object]) -> None: ...

    def list_audit(self, *, run_id: str | None = None) -> list[dict[str, object]]: ...

    def close(self) -> None: ...
